ALTER TABLE "contacts" DROP CONSTRAINT "contacts_properties_object_check";
ALTER TABLE "contacts" DROP CONSTRAINT "contacts_last_name_length_check";
ALTER TABLE "contacts" DROP CONSTRAINT "contacts_first_name_length_check";
DROP INDEX "contacts_org_id_idx";
DROP INDEX "contacts_org_id_email_unique";
ALTER TABLE "contacts" DROP CONSTRAINT "contacts_org_id_orgs_id_fk";
ALTER TABLE "topics" DROP CONSTRAINT "topics_org_id_orgs_id_fk";
ALTER TABLE "segments" DROP CONSTRAINT "segments_org_id_orgs_id_fk";
ALTER TABLE "contact_topics" DROP CONSTRAINT "contact_topics_topic_id_topics_id_fk";
ALTER TABLE "contact_topics" DROP CONSTRAINT "contact_topics_contact_id_contacts_id_fk";
ALTER TABLE "contact_segments" DROP CONSTRAINT "contact_segments_segment_id_segments_id_fk";
ALTER TABLE "contact_segments" DROP CONSTRAINT "contact_segments_contact_id_contacts_id_fk";
ALTER TABLE "contact_properties" DROP CONSTRAINT "contact_properties_org_id_orgs_id_fk";
ALTER TABLE "contact_imports" DROP CONSTRAINT "contact_imports_org_id_orgs_id_fk";
ALTER TABLE "contacts" DROP COLUMN "properties";
ALTER TABLE "contacts" DROP COLUMN "last_name";
ALTER TABLE "contacts" DROP COLUMN "first_name";
ALTER TABLE "contacts" DROP COLUMN "org_id";
ALTER TABLE "contacts" ALTER COLUMN "audience_id" SET NOT NULL;
DROP TABLE "topics";
DROP TABLE "segments";
DROP TABLE "contact_topics";
DROP TABLE "contact_segments";
DROP TABLE "contact_properties";
DROP TABLE "contact_imports";
