/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ContactImport,
    ContactImportInput,
    ContactImportListEnvelope,
    ContactSegmentListEnvelope,
    ContactTopicListEnvelope,
    ContactTopicsUpdateInput,
    CreateContactImportRequest,
    DeletedResource,
    ErrorEnvelope,
    OrgContact,
    OrgContactInput,
    OrgContactListEnvelope,
    OrgContactUpdateInput,
} from '../models/index';

export interface AddContactToSegmentRequest {
    contactId: string;
    segmentId: string;
}

export interface CreateContactImportOperationRequest {
    contactImportInput: ContactImportInput;
}

export interface CreateOrgContactRequest {
    orgContactInput: OrgContactInput;
}

export interface DeleteOrgContactRequest {
    contactId: string;
}

export interface GetContactImportRequest {
    importId: string;
}

export interface GetOrgContactRequest {
    contactId: string;
}

export interface ListContactSegmentsRequest {
    contactId: string;
}

export interface ListContactTopicsRequest {
    contactId: string;
}

export interface ListOrgContactsRequest {
    segmentId?: string;
    limit?: number;
}

export interface RemoveContactFromSegmentRequest {
    contactId: string;
    segmentId: string;
}

export interface UpdateContactTopicsRequest {
    contactId: string;
    contactTopicsUpdateInput: ContactTopicsUpdateInput;
}

export interface UpdateOrgContactRequest {
    contactId: string;
    orgContactUpdateInput: OrgContactUpdateInput;
}

/**
 * 
 */
export class ContactsApi extends runtime.BaseAPI {

    /**
     * Creates request options for addContactToSegment without sending the request
     */
    async addContactToSegmentRequestOpts(requestParameters: AddContactToSegmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling addContactToSegment().'
            );
        }

        if (requestParameters['segmentId'] == null) {
            throw new runtime.RequiredError(
                'segmentId',
                'Required parameter "segmentId" was null or undefined when calling addContactToSegment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/{contactId}/segments/{segmentId}`;
        urlPath = urlPath.replace('{contactId}', encodeURIComponent(String(requestParameters['contactId'])));
        urlPath = urlPath.replace('{segmentId}', encodeURIComponent(String(requestParameters['segmentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Add one contact to one segment
     */
    async addContactToSegmentRaw(requestParameters: AddContactToSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgContact>> {
        const requestOptions = await this.addContactToSegmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Add one contact to one segment
     */
    async addContactToSegment(requestParameters: AddContactToSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgContact> {
        const response = await this.addContactToSegmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createContactImport without sending the request
     */
    async createContactImportRequestOpts(requestParameters: CreateContactImportOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactImportInput'] == null) {
            throw new runtime.RequiredError(
                'contactImportInput',
                'Required parameter "contactImportInput" was null or undefined when calling createContactImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/imports`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['contactImportInput'],
        };
    }

    /**
     * Import contacts from CSV
     */
    async createContactImportRaw(requestParameters: CreateContactImportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactImport>> {
        const requestOptions = await this.createContactImportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Import contacts from CSV
     */
    async createContactImport(requestParameters: CreateContactImportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactImport> {
        const response = await this.createContactImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createOrgContact without sending the request
     */
    async createOrgContactRequestOpts(requestParameters: CreateOrgContactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgContactInput'] == null) {
            throw new runtime.RequiredError(
                'orgContactInput',
                'Required parameter "orgContactInput" was null or undefined when calling createOrgContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['orgContactInput'],
        };
    }

    /**
     * Create one contact
     */
    async createOrgContactRaw(requestParameters: CreateOrgContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgContact>> {
        const requestOptions = await this.createOrgContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create one contact
     */
    async createOrgContact(requestParameters: CreateOrgContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgContact> {
        const response = await this.createOrgContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteOrgContact without sending the request
     */
    async deleteOrgContactRequestOpts(requestParameters: DeleteOrgContactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling deleteOrgContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/{contactId}`;
        urlPath = urlPath.replace('{contactId}', encodeURIComponent(String(requestParameters['contactId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete one contact by ID or email
     */
    async deleteOrgContactRaw(requestParameters: DeleteOrgContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResource>> {
        const requestOptions = await this.deleteOrgContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Delete one contact by ID or email
     */
    async deleteOrgContact(requestParameters: DeleteOrgContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResource> {
        const response = await this.deleteOrgContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getContactImport without sending the request
     */
    async getContactImportRequestOpts(requestParameters: GetContactImportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['importId'] == null) {
            throw new runtime.RequiredError(
                'importId',
                'Required parameter "importId" was null or undefined when calling getContactImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/imports/{importId}`;
        urlPath = urlPath.replace('{importId}', encodeURIComponent(String(requestParameters['importId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one contact import
     */
    async getContactImportRaw(requestParameters: GetContactImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactImport>> {
        const requestOptions = await this.getContactImportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get one contact import
     */
    async getContactImport(requestParameters: GetContactImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactImport> {
        const response = await this.getContactImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrgContact without sending the request
     */
    async getOrgContactRequestOpts(requestParameters: GetOrgContactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling getOrgContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/{contactId}`;
        urlPath = urlPath.replace('{contactId}', encodeURIComponent(String(requestParameters['contactId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one contact by ID or email
     */
    async getOrgContactRaw(requestParameters: GetOrgContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgContact>> {
        const requestOptions = await this.getOrgContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get one contact by ID or email
     */
    async getOrgContact(requestParameters: GetOrgContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgContact> {
        const response = await this.getOrgContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listContactImports without sending the request
     */
    async listContactImportsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/imports`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List contact imports
     */
    async listContactImportsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactImportListEnvelope>> {
        const requestOptions = await this.listContactImportsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List contact imports
     */
    async listContactImports(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactImportListEnvelope> {
        const response = await this.listContactImportsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listContactSegments without sending the request
     */
    async listContactSegmentsRequestOpts(requestParameters: ListContactSegmentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling listContactSegments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/{contactId}/segments`;
        urlPath = urlPath.replace('{contactId}', encodeURIComponent(String(requestParameters['contactId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List one contact\'s segments
     */
    async listContactSegmentsRaw(requestParameters: ListContactSegmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactSegmentListEnvelope>> {
        const requestOptions = await this.listContactSegmentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List one contact\'s segments
     */
    async listContactSegments(requestParameters: ListContactSegmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactSegmentListEnvelope> {
        const response = await this.listContactSegmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listContactTopics without sending the request
     */
    async listContactTopicsRequestOpts(requestParameters: ListContactTopicsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling listContactTopics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/{contactId}/topics`;
        urlPath = urlPath.replace('{contactId}', encodeURIComponent(String(requestParameters['contactId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List one contact\'s topics
     */
    async listContactTopicsRaw(requestParameters: ListContactTopicsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactTopicListEnvelope>> {
        const requestOptions = await this.listContactTopicsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List one contact\'s topics
     */
    async listContactTopics(requestParameters: ListContactTopicsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactTopicListEnvelope> {
        const response = await this.listContactTopicsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrgContacts without sending the request
     */
    async listOrgContactsRequestOpts(requestParameters: ListOrgContactsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['segmentId'] != null) {
            queryParameters['segment_id'] = requestParameters['segmentId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List contacts
     */
    async listOrgContactsRaw(requestParameters: ListOrgContactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgContactListEnvelope>> {
        const requestOptions = await this.listOrgContactsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List contacts
     */
    async listOrgContacts(requestParameters: ListOrgContactsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgContactListEnvelope> {
        const response = await this.listOrgContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeContactFromSegment without sending the request
     */
    async removeContactFromSegmentRequestOpts(requestParameters: RemoveContactFromSegmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling removeContactFromSegment().'
            );
        }

        if (requestParameters['segmentId'] == null) {
            throw new runtime.RequiredError(
                'segmentId',
                'Required parameter "segmentId" was null or undefined when calling removeContactFromSegment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/{contactId}/segments/{segmentId}`;
        urlPath = urlPath.replace('{contactId}', encodeURIComponent(String(requestParameters['contactId'])));
        urlPath = urlPath.replace('{segmentId}', encodeURIComponent(String(requestParameters['segmentId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove one contact from one segment
     */
    async removeContactFromSegmentRaw(requestParameters: RemoveContactFromSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgContact>> {
        const requestOptions = await this.removeContactFromSegmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Remove one contact from one segment
     */
    async removeContactFromSegment(requestParameters: RemoveContactFromSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgContact> {
        const response = await this.removeContactFromSegmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateContactTopics without sending the request
     */
    async updateContactTopicsRequestOpts(requestParameters: UpdateContactTopicsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling updateContactTopics().'
            );
        }

        if (requestParameters['contactTopicsUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'contactTopicsUpdateInput',
                'Required parameter "contactTopicsUpdateInput" was null or undefined when calling updateContactTopics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/{contactId}/topics`;
        urlPath = urlPath.replace('{contactId}', encodeURIComponent(String(requestParameters['contactId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['contactTopicsUpdateInput'],
        };
    }

    /**
     * Replace one contact\'s topic subscriptions
     */
    async updateContactTopicsRaw(requestParameters: UpdateContactTopicsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgContact>> {
        const requestOptions = await this.updateContactTopicsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Replace one contact\'s topic subscriptions
     */
    async updateContactTopics(requestParameters: UpdateContactTopicsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgContact> {
        const response = await this.updateContactTopicsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateOrgContact without sending the request
     */
    async updateOrgContactRequestOpts(requestParameters: UpdateOrgContactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling updateOrgContact().'
            );
        }

        if (requestParameters['orgContactUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'orgContactUpdateInput',
                'Required parameter "orgContactUpdateInput" was null or undefined when calling updateOrgContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contacts/{contactId}`;
        urlPath = urlPath.replace('{contactId}', encodeURIComponent(String(requestParameters['contactId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['orgContactUpdateInput'],
        };
    }

    /**
     * Update one contact by ID or email
     */
    async updateOrgContactRaw(requestParameters: UpdateOrgContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgContact>> {
        const requestOptions = await this.updateOrgContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update one contact by ID or email
     */
    async updateOrgContact(requestParameters: UpdateOrgContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgContact> {
        const response = await this.updateOrgContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
