/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ContactProperty,
    ContactPropertyInput,
    ContactPropertyListEnvelope,
    ContactPropertyUpdateInput,
    DeletedResource,
    ErrorEnvelope,
} from '../models/index';

export interface CreateContactPropertyRequest {
    contactPropertyInput: ContactPropertyInput;
}

export interface DeleteContactPropertyRequest {
    propertyId: string;
}

export interface GetContactPropertyRequest {
    propertyId: string;
}

export interface UpdateContactPropertyRequest {
    propertyId: string;
    contactPropertyUpdateInput: ContactPropertyUpdateInput;
}

/**
 * 
 */
export class ContactPropertiesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createContactProperty without sending the request
     */
    async createContactPropertyRequestOpts(requestParameters: CreateContactPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactPropertyInput'] == null) {
            throw new runtime.RequiredError(
                'contactPropertyInput',
                'Required parameter "contactPropertyInput" was null or undefined when calling createContactProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contact-properties`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['contactPropertyInput'],
        };
    }

    /**
     * Create one contact property
     */
    async createContactPropertyRaw(requestParameters: CreateContactPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactProperty>> {
        const requestOptions = await this.createContactPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create one contact property
     */
    async createContactProperty(requestParameters: CreateContactPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactProperty> {
        const response = await this.createContactPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteContactProperty without sending the request
     */
    async deleteContactPropertyRequestOpts(requestParameters: DeleteContactPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling deleteContactProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contact-properties/{propertyId}`;
        urlPath = urlPath.replace('{propertyId}', encodeURIComponent(String(requestParameters['propertyId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete one contact property
     */
    async deleteContactPropertyRaw(requestParameters: DeleteContactPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResource>> {
        const requestOptions = await this.deleteContactPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Delete one contact property
     */
    async deleteContactProperty(requestParameters: DeleteContactPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResource> {
        const response = await this.deleteContactPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getContactProperty without sending the request
     */
    async getContactPropertyRequestOpts(requestParameters: GetContactPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getContactProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contact-properties/{propertyId}`;
        urlPath = urlPath.replace('{propertyId}', encodeURIComponent(String(requestParameters['propertyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one contact property
     */
    async getContactPropertyRaw(requestParameters: GetContactPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactProperty>> {
        const requestOptions = await this.getContactPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get one contact property
     */
    async getContactProperty(requestParameters: GetContactPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactProperty> {
        const response = await this.getContactPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listContactProperties without sending the request
     */
    async listContactPropertiesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contact-properties`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List contact properties
     */
    async listContactPropertiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactPropertyListEnvelope>> {
        const requestOptions = await this.listContactPropertiesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List contact properties
     */
    async listContactProperties(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactPropertyListEnvelope> {
        const response = await this.listContactPropertiesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateContactProperty without sending the request
     */
    async updateContactPropertyRequestOpts(requestParameters: UpdateContactPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling updateContactProperty().'
            );
        }

        if (requestParameters['contactPropertyUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'contactPropertyUpdateInput',
                'Required parameter "contactPropertyUpdateInput" was null or undefined when calling updateContactProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/contact-properties/{propertyId}`;
        urlPath = urlPath.replace('{propertyId}', encodeURIComponent(String(requestParameters['propertyId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['contactPropertyUpdateInput'],
        };
    }

    /**
     * Update one contact property
     */
    async updateContactPropertyRaw(requestParameters: UpdateContactPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactProperty>> {
        const requestOptions = await this.updateContactPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update one contact property
     */
    async updateContactProperty(requestParameters: UpdateContactPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactProperty> {
        const response = await this.updateContactPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
