/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    CustomEvent,
    CustomEventInput,
    CustomEventListEnvelope,
    CustomEventUpdateInput,
    DeletedResource,
    ErrorEnvelope,
    EventOccurrenceEnvelope,
    SendEventInput,
} from '../models/index';

export interface CreateEventRequest {
    customEventInput: CustomEventInput;
}

export interface DeleteEventRequest {
    identifier: string;
}

export interface GetEventRequest {
    identifier: string;
}

export interface SendEventRequest {
    sendEventInput: SendEventInput;
}

export interface UpdateEventRequest {
    identifier: string;
    customEventUpdateInput: CustomEventUpdateInput;
}

/**
 * 
 */
export class CustomEventsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createEvent without sending the request
     */
    async createEventRequestOpts(requestParameters: CreateEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customEventInput'] == null) {
            throw new runtime.RequiredError(
                'customEventInput',
                'Required parameter "customEventInput" was null or undefined when calling createEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/events`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['customEventInput'],
        };
    }

    /**
     * Define one custom event
     */
    async createEventRaw(requestParameters: CreateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomEvent>> {
        const requestOptions = await this.createEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Define one custom event
     */
    async createEvent(requestParameters: CreateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomEvent> {
        const response = await this.createEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteEvent without sending the request
     */
    async deleteEventRequestOpts(requestParameters: DeleteEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling deleteEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/events/{identifier}`;
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete one custom event
     */
    async deleteEventRaw(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResource>> {
        const requestOptions = await this.deleteEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Delete one custom event
     */
    async deleteEvent(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResource> {
        const response = await this.deleteEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEvent without sending the request
     */
    async getEventRequestOpts(requestParameters: GetEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling getEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/events/{identifier}`;
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one custom event
     */
    async getEventRaw(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomEvent>> {
        const requestOptions = await this.getEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get one custom event
     */
    async getEvent(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomEvent> {
        const response = await this.getEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEvents without sending the request
     */
    async listEventsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List custom events
     */
    async listEventsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomEventListEnvelope>> {
        const requestOptions = await this.listEventsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List custom events
     */
    async listEvents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomEventListEnvelope> {
        const response = await this.listEventsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEvent without sending the request
     */
    async sendEventRequestOpts(requestParameters: SendEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendEventInput'] == null) {
            throw new runtime.RequiredError(
                'sendEventInput',
                'Required parameter "sendEventInput" was null or undefined when calling sendEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/events/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sendEventInput'],
        };
    }

    /**
     * Records the occurrence and runs matching enabled automations.
     * Send one custom event
     */
    async sendEventRaw(requestParameters: SendEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventOccurrenceEnvelope>> {
        const requestOptions = await this.sendEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Records the occurrence and runs matching enabled automations.
     * Send one custom event
     */
    async sendEvent(requestParameters: SendEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventOccurrenceEnvelope> {
        const response = await this.sendEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEvent without sending the request
     */
    async updateEventRequestOpts(requestParameters: UpdateEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['identifier'] == null) {
            throw new runtime.RequiredError(
                'identifier',
                'Required parameter "identifier" was null or undefined when calling updateEvent().'
            );
        }

        if (requestParameters['customEventUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'customEventUpdateInput',
                'Required parameter "customEventUpdateInput" was null or undefined when calling updateEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/events/{identifier}`;
        urlPath = urlPath.replace('{identifier}', encodeURIComponent(String(requestParameters['identifier'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['customEventUpdateInput'],
        };
    }

    /**
     * Update one custom event
     */
    async updateEventRaw(requestParameters: UpdateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomEvent>> {
        const requestOptions = await this.updateEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update one custom event
     */
    async updateEvent(requestParameters: UpdateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomEvent> {
        const response = await this.updateEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
