/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    Email,
    EmailAttachment,
    EmailBatchEnvelope,
    EmailListEnvelope,
    EmailMetrics,
    ErrorEnvelope,
    QueuedEmail,
    RateLimitErrorEnvelope,
    ReceiveInboundEmailInput,
    ReceivedEmail,
    ReceivedEmailAccepted,
    ReceivedEmailDiscarded,
    RescheduleEmailInput,
    RetrievedEmailAttachmentListEnvelope,
    SendEmailInput,
    ShareEmailInput,
    SharedEmail,
    SharedEmailContent,
} from '../models/index';

export interface CancelEmailRequest {
    emailId: string;
}

export interface DownloadAttachmentRequest {
    token: string;
}

export interface GetEmailRequest {
    emailId: string;
}

export interface GetEmailAttachmentRequest {
    emailId: string;
    attachmentId: string;
}

export interface GetEmailMetricsRequest {
    startDate?: string;
    endDate?: string;
    timezone?: string;
    granularity?: GetEmailMetricsGranularityEnum;
    metrics?: string;
    dimensions?: string;
    domainId?: string;
    emailId?: string;
    broadcastId?: string;
}

export interface GetReceivedEmailRequest {
    emailId: string;
}

export interface GetReceivedEmailAttachmentRequest {
    emailId: string;
    attachmentId: string;
}

export interface GetSharedEmailRequest {
    token: string;
}

export interface ListEmailAttachmentsRequest {
    emailId: string;
}

export interface ListEmailsRequest {
    page?: number;
    limit?: number;
}

export interface ListReceivedEmailAttachmentsRequest {
    emailId: string;
}

export interface ReceiveInboundEmailRequest {
    receiveInboundEmailInput: ReceiveInboundEmailInput;
}

export interface RescheduleEmailRequest {
    emailId: string;
    rescheduleEmailInput: RescheduleEmailInput;
}

export interface SendEmailRequest {
    sendEmailInput: SendEmailInput;
    idempotencyKey?: string;
}

export interface SendEmailBatchRequest {
    sendEmailInput: Array<SendEmailInput>;
}

export interface ShareEmailRequest {
    emailId: string;
    shareEmailInput?: ShareEmailInput;
}

/**
 * 
 */
export class EmailsApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelEmail without sending the request
     */
    async cancelEmailRequestOpts(requestParameters: CancelEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling cancelEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/{emailId}/cancel`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marks a still-queued message cancelled so the worker never hands it to the provider. Cancelling after send is rejected.
     * Cancel a queued email
     */
    async cancelEmailRaw(requestParameters: CancelEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Email>> {
        const requestOptions = await this.cancelEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Marks a still-queued message cancelled so the worker never hands it to the provider. Cancelling after send is rejected.
     * Cancel a queued email
     */
    async cancelEmail(requestParameters: CancelEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Email> {
        const response = await this.cancelEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadAttachment without sending the request
     */
    async downloadAttachmentRequestOpts(requestParameters: DownloadAttachmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling downloadAttachment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/attachments/download`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Public signed link access. No API key required.
     * Download shared attachment bytes
     */
    async downloadAttachmentRaw(requestParameters: DownloadAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadAttachmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Public signed link access. No API key required.
     * Download shared attachment bytes
     */
    async downloadAttachment(requestParameters: DownloadAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadAttachmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEmail without sending the request
     */
    async getEmailRequestOpts(requestParameters: GetEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling getEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/{emailId}`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one message from the organization and environment selected by the bearer key. Attachment metadata is safe; stored bytes, hashes, and storage keys are never returned.
     * Get one email
     */
    async getEmailRaw(requestParameters: GetEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Email>> {
        const requestOptions = await this.getEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns one message from the organization and environment selected by the bearer key. Attachment metadata is safe; stored bytes, hashes, and storage keys are never returned.
     * Get one email
     */
    async getEmail(requestParameters: GetEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Email> {
        const response = await this.getEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEmailAttachment without sending the request
     */
    async getEmailAttachmentRequestOpts(requestParameters: GetEmailAttachmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling getEmailAttachment().'
            );
        }

        if (requestParameters['attachmentId'] == null) {
            throw new runtime.RequiredError(
                'attachmentId',
                'Required parameter "attachmentId" was null or undefined when calling getEmailAttachment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/{emailId}/attachments/{attachmentId}`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));
        urlPath = urlPath.replace('{attachmentId}', encodeURIComponent(String(requestParameters['attachmentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one email attachment
     */
    async getEmailAttachmentRaw(requestParameters: GetEmailAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailAttachment>> {
        const requestOptions = await this.getEmailAttachmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get one email attachment
     */
    async getEmailAttachment(requestParameters: GetEmailAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailAttachment> {
        const response = await this.getEmailAttachmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEmailMetrics without sending the request
     */
    async getEmailMetricsRequestOpts(requestParameters: GetEmailMetricsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = requestParameters['startDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = requestParameters['endDate'];
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        if (requestParameters['metrics'] != null) {
            queryParameters['metrics'] = requestParameters['metrics'];
        }

        if (requestParameters['dimensions'] != null) {
            queryParameters['dimensions'] = requestParameters['dimensions'];
        }

        if (requestParameters['domainId'] != null) {
            queryParameters['domain_id'] = requestParameters['domainId'];
        }

        if (requestParameters['emailId'] != null) {
            queryParameters['email_id'] = requestParameters['emailId'];
        }

        if (requestParameters['broadcastId'] != null) {
            queryParameters['broadcast_id'] = requestParameters['broadcastId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/metrics`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Totals always cover the range; data rows appear when a dimension is requested. Email and broadcast dimensions cannot be combined.
     * Aggregate email metrics
     */
    async getEmailMetricsRaw(requestParameters: GetEmailMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailMetrics>> {
        const requestOptions = await this.getEmailMetricsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Totals always cover the range; data rows appear when a dimension is requested. Email and broadcast dimensions cannot be combined.
     * Aggregate email metrics
     */
    async getEmailMetrics(requestParameters: GetEmailMetricsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailMetrics> {
        const response = await this.getEmailMetricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getReceivedEmail without sending the request
     */
    async getReceivedEmailRequestOpts(requestParameters: GetReceivedEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling getReceivedEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/received-emails/{emailId}`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the stored inbound email for the organization and environment selected by the bearer key. Support desks use this after `email.received` to read the customer reply body.
     * Get one inbound email
     */
    async getReceivedEmailRaw(requestParameters: GetReceivedEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceivedEmail>> {
        const requestOptions = await this.getReceivedEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the stored inbound email for the organization and environment selected by the bearer key. Support desks use this after `email.received` to read the customer reply body.
     * Get one inbound email
     */
    async getReceivedEmail(requestParameters: GetReceivedEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceivedEmail> {
        const response = await this.getReceivedEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getReceivedEmailAttachment without sending the request
     */
    async getReceivedEmailAttachmentRequestOpts(requestParameters: GetReceivedEmailAttachmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling getReceivedEmailAttachment().'
            );
        }

        if (requestParameters['attachmentId'] == null) {
            throw new runtime.RequiredError(
                'attachmentId',
                'Required parameter "attachmentId" was null or undefined when calling getReceivedEmailAttachment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/received-emails/{emailId}/attachments/{attachmentId}`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));
        urlPath = urlPath.replace('{attachmentId}', encodeURIComponent(String(requestParameters['attachmentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one inbound email attachment
     */
    async getReceivedEmailAttachmentRaw(requestParameters: GetReceivedEmailAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailAttachment>> {
        const requestOptions = await this.getReceivedEmailAttachmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get one inbound email attachment
     */
    async getReceivedEmailAttachment(requestParameters: GetReceivedEmailAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailAttachment> {
        const response = await this.getReceivedEmailAttachmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSharedEmail without sending the request
     */
    async getSharedEmailRequestOpts(requestParameters: GetSharedEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling getSharedEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/shared/{token}`;
        urlPath = urlPath.replace('{token}', encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Public signed link access. No API key required.
     * Read a shared email
     */
    async getSharedEmailRaw(requestParameters: GetSharedEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharedEmailContent>> {
        const requestOptions = await this.getSharedEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Public signed link access. No API key required.
     * Read a shared email
     */
    async getSharedEmail(requestParameters: GetSharedEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharedEmailContent> {
        const response = await this.getSharedEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEmailAttachments without sending the request
     */
    async listEmailAttachmentsRequestOpts(requestParameters: ListEmailAttachmentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling listEmailAttachments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/{emailId}/attachments`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List one email\'s attachments
     */
    async listEmailAttachmentsRaw(requestParameters: ListEmailAttachmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetrievedEmailAttachmentListEnvelope>> {
        const requestOptions = await this.listEmailAttachmentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List one email\'s attachments
     */
    async listEmailAttachments(requestParameters: ListEmailAttachmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetrievedEmailAttachmentListEnvelope> {
        const response = await this.listEmailAttachmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEmails without sending the request
     */
    async listEmailsRequestOpts(requestParameters: ListEmailsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists messages in the organization and environment selected by the bearer key, newest first. Timestamps are RFC 3339 UTC. Attachment bytes, hashes, and storage keys are never returned.
     * List emails
     */
    async listEmailsRaw(requestParameters: ListEmailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailListEnvelope>> {
        const requestOptions = await this.listEmailsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Lists messages in the organization and environment selected by the bearer key, newest first. Timestamps are RFC 3339 UTC. Attachment bytes, hashes, and storage keys are never returned.
     * List emails
     */
    async listEmails(requestParameters: ListEmailsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailListEnvelope> {
        const response = await this.listEmailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listReceivedEmailAttachments without sending the request
     */
    async listReceivedEmailAttachmentsRequestOpts(requestParameters: ListReceivedEmailAttachmentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling listReceivedEmailAttachments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/received-emails/{emailId}/attachments`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List one inbound email\'s attachments
     */
    async listReceivedEmailAttachmentsRaw(requestParameters: ListReceivedEmailAttachmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetrievedEmailAttachmentListEnvelope>> {
        const requestOptions = await this.listReceivedEmailAttachmentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List one inbound email\'s attachments
     */
    async listReceivedEmailAttachments(requestParameters: ListReceivedEmailAttachmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetrievedEmailAttachmentListEnvelope> {
        const response = await this.listReceivedEmailAttachmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiveInboundEmail without sending the request
     */
    async receiveInboundEmailRequestOpts(requestParameters: ReceiveInboundEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['receiveInboundEmailInput'] == null) {
            throw new runtime.RequiredError(
                'receiveInboundEmailInput',
                'Required parameter "receiveInboundEmailInput" was null or undefined when calling receiveInboundEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/received-emails`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['receiveInboundEmailInput'],
        };
    }

    /**
     * Accepts a raw RFC 822 `email` string or parsed from/to/subject/html/text fields. Live keys require at least one recipient domain to be a verified organization sending domain, including plus-addresses used by support desks. Returned mail such as out-of-office auto-replies and bounce reports is discarded without storage or `email.received`. A configured organization webhook receives `email.received` with routing metadata only; fetch the body with GET /api/v1/received-emails/{emailId}.
     * Store one inbound email
     */
    async receiveInboundEmailRaw(requestParameters: ReceiveInboundEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceivedEmailAccepted>> {
        const requestOptions = await this.receiveInboundEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Accepts a raw RFC 822 `email` string or parsed from/to/subject/html/text fields. Live keys require at least one recipient domain to be a verified organization sending domain, including plus-addresses used by support desks. Returned mail such as out-of-office auto-replies and bounce reports is discarded without storage or `email.received`. A configured organization webhook receives `email.received` with routing metadata only; fetch the body with GET /api/v1/received-emails/{emailId}.
     * Store one inbound email
     */
    async receiveInboundEmail(requestParameters: ReceiveInboundEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceivedEmailAccepted> {
        const response = await this.receiveInboundEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rescheduleEmail without sending the request
     */
    async rescheduleEmailRequestOpts(requestParameters: RescheduleEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling rescheduleEmail().'
            );
        }

        if (requestParameters['rescheduleEmailInput'] == null) {
            throw new runtime.RequiredError(
                'rescheduleEmailInput',
                'Required parameter "rescheduleEmailInput" was null or undefined when calling rescheduleEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/{emailId}`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['rescheduleEmailInput'],
        };
    }

    /**
     * Moves a still-queued message to a new scheduled_at instant. Only queued messages can be rescheduled; sent, failed, and cancelled messages are rejected. Past values make the message due immediately.
     * Reschedule a queued email
     */
    async rescheduleEmailRaw(requestParameters: RescheduleEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Email>> {
        const requestOptions = await this.rescheduleEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Moves a still-queued message to a new scheduled_at instant. Only queued messages can be rescheduled; sent, failed, and cancelled messages are rejected. Past values make the message due immediately.
     * Reschedule a queued email
     */
    async rescheduleEmail(requestParameters: RescheduleEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Email> {
        const response = await this.rescheduleEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEmail without sending the request
     */
    async sendEmailRequestOpts(requestParameters: SendEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendEmailInput'] == null) {
            throw new runtime.RequiredError(
                'sendEmailInput',
                'Required parameter "sendEmailInput" was null or undefined when calling sendEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sendEmailInput'],
        };
    }

    /**
     * Validates and stores one provider-neutral message. Test keys always use the isolated test sink. Live keys require a verified organization domain, active DKIM state, and configured credentials for the resolved organization default or domain override. Provider choice is snapshotted on the queued message. Cloudflare Email Service remains responsible for provider-owned DKIM and ARC signatures. Idempotency may be supplied in the header or JSON body and is active for 24 hours per API key. A future scheduled_at holds the message until its time; past values send immediately.
     * Queue one email
     */
    async sendEmailRaw(requestParameters: SendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueuedEmail>> {
        const requestOptions = await this.sendEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Validates and stores one provider-neutral message. Test keys always use the isolated test sink. Live keys require a verified organization domain, active DKIM state, and configured credentials for the resolved organization default or domain override. Provider choice is snapshotted on the queued message. Cloudflare Email Service remains responsible for provider-owned DKIM and ARC signatures. Idempotency may be supplied in the header or JSON body and is active for 24 hours per API key. A future scheduled_at holds the message until its time; past values send immediately.
     * Queue one email
     */
    async sendEmail(requestParameters: SendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueuedEmail> {
        const response = await this.sendEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEmailBatch without sending the request
     */
    async sendEmailBatchRequestOpts(requestParameters: SendEmailBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendEmailInput'] == null) {
            throw new runtime.RequiredError(
                'sendEmailInput',
                'Required parameter "sendEmailInput" was null or undefined when calling sendEmailBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/batch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sendEmailInput'],
        };
    }

    /**
     * Accepts a JSON array of 1 to 100 send objects. Each item is validated independently. A fully valid batch returns 200. Mixed success returns 207 and keeps accepted neighbors. An entirely rate-limited batch returns 429. Attachments and Idempotency-Key are not supported on this route.
     * Queue one to 100 emails
     */
    async sendEmailBatchRaw(requestParameters: SendEmailBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailBatchEnvelope>> {
        const requestOptions = await this.sendEmailBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Accepts a JSON array of 1 to 100 send objects. Each item is validated independently. A fully valid batch returns 200. Mixed success returns 207 and keeps accepted neighbors. An entirely rate-limited batch returns 429. Attachments and Idempotency-Key are not supported on this route.
     * Queue one to 100 emails
     */
    async sendEmailBatch(requestParameters: SendEmailBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailBatchEnvelope> {
        const response = await this.sendEmailBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for shareEmail without sending the request
     */
    async shareEmailRequestOpts(requestParameters: ShareEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling shareEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/{emailId}/share`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['shareEmailInput'],
        };
    }

    /**
     * Links expire after at most 48 hours.
     * Create a shareable link for one email
     */
    async shareEmailRaw(requestParameters: ShareEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharedEmail>> {
        const requestOptions = await this.shareEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Links expire after at most 48 hours.
     * Create a shareable link for one email
     */
    async shareEmail(requestParameters: ShareEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharedEmail> {
        const response = await this.shareEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetEmailMetricsGranularityEnum = {
    hourly: 'hourly',
    daily: 'daily',
    weekly: 'weekly',
    monthly: 'monthly'
} as const;
export type GetEmailMetricsGranularityEnum = typeof GetEmailMetricsGranularityEnum[keyof typeof GetEmailMetricsGranularityEnum];
