/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    DeletedResource,
    ErrorEnvelope,
    Segment,
    SegmentInput,
    SegmentListEnvelope,
} from '../models/index';

export interface CreateSegmentRequest {
    segmentInput: SegmentInput;
}

export interface DeleteSegmentRequest {
    segmentId: string;
}

export interface GetSegmentRequest {
    segmentId: string;
}

export interface UpdateSegmentRequest {
    segmentId: string;
    segmentInput: SegmentInput;
}

/**
 * 
 */
export class SegmentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSegment without sending the request
     */
    async createSegmentRequestOpts(requestParameters: CreateSegmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['segmentInput'] == null) {
            throw new runtime.RequiredError(
                'segmentInput',
                'Required parameter "segmentInput" was null or undefined when calling createSegment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/segments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['segmentInput'],
        };
    }

    /**
     * Create one segment
     */
    async createSegmentRaw(requestParameters: CreateSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Segment>> {
        const requestOptions = await this.createSegmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create one segment
     */
    async createSegment(requestParameters: CreateSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Segment> {
        const response = await this.createSegmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSegment without sending the request
     */
    async deleteSegmentRequestOpts(requestParameters: DeleteSegmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['segmentId'] == null) {
            throw new runtime.RequiredError(
                'segmentId',
                'Required parameter "segmentId" was null or undefined when calling deleteSegment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/segments/{segmentId}`;
        urlPath = urlPath.replace('{segmentId}', encodeURIComponent(String(requestParameters['segmentId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete one segment
     */
    async deleteSegmentRaw(requestParameters: DeleteSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResource>> {
        const requestOptions = await this.deleteSegmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Delete one segment
     */
    async deleteSegment(requestParameters: DeleteSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResource> {
        const response = await this.deleteSegmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSegment without sending the request
     */
    async getSegmentRequestOpts(requestParameters: GetSegmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['segmentId'] == null) {
            throw new runtime.RequiredError(
                'segmentId',
                'Required parameter "segmentId" was null or undefined when calling getSegment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/segments/{segmentId}`;
        urlPath = urlPath.replace('{segmentId}', encodeURIComponent(String(requestParameters['segmentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one segment
     */
    async getSegmentRaw(requestParameters: GetSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Segment>> {
        const requestOptions = await this.getSegmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get one segment
     */
    async getSegment(requestParameters: GetSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Segment> {
        const response = await this.getSegmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSegments without sending the request
     */
    async listSegmentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/segments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List segments
     */
    async listSegmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SegmentListEnvelope>> {
        const requestOptions = await this.listSegmentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List segments
     */
    async listSegments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SegmentListEnvelope> {
        const response = await this.listSegmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSegment without sending the request
     */
    async updateSegmentRequestOpts(requestParameters: UpdateSegmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['segmentId'] == null) {
            throw new runtime.RequiredError(
                'segmentId',
                'Required parameter "segmentId" was null or undefined when calling updateSegment().'
            );
        }

        if (requestParameters['segmentInput'] == null) {
            throw new runtime.RequiredError(
                'segmentInput',
                'Required parameter "segmentInput" was null or undefined when calling updateSegment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/segments/{segmentId}`;
        urlPath = urlPath.replace('{segmentId}', encodeURIComponent(String(requestParameters['segmentId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['segmentInput'],
        };
    }

    /**
     * Update one segment
     */
    async updateSegmentRaw(requestParameters: UpdateSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Segment>> {
        const requestOptions = await this.updateSegmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update one segment
     */
    async updateSegment(requestParameters: UpdateSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Segment> {
        const response = await this.updateSegmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
